<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_01_Login_With_Data</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>1445b8f3-5310-407e-ad03-5d8da75a44f4</testSuiteGuid>
   <testCaseLink>
      <guid>27fe2f20-5ca9-4b1b-8697-2fb4b0b15acc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Cura Healthcare/TC_02_Login_Data</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>6ff02e60-6144-4e19-aaa3-b80f7bac05bd</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Data Login/Data Login</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>6ff02e60-6144-4e19-aaa3-b80f7bac05bd</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>84f087e4-1b85-40e1-8efb-8847749ade8b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>6ff02e60-6144-4e19-aaa3-b80f7bac05bd</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>f785a774-3fd7-4535-af70-f3e0ab529b74</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
