<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>button_Reset_Password</description>
   <name>button_Reset_Password</name>
   <tag></tag>
   <elementGuidId>d1af2d7f-dac9-4d7f-aa49-0fc99325086f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;app&quot;]/div[1]/div[1]/div/form/div[2]/button[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
