<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>button_Cancel_Forgot_Password</description>
   <name>button_Cancel_Forgot_Password</name>
   <tag></tag>
   <elementGuidId>69813458-3c5e-4c92-8937-5ed6df737558</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;app&quot;]/div[1]/div[1]/div/form/div[2]/button[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
