<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>input_Username_Reset_Password</description>
   <name>input_Username_Reset_Password</name>
   <tag></tag>
   <elementGuidId>9d2b6b74-3098-4a44-b660-c97c2ec1d87c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;app&quot;]/div[1]/div[1]/div/form/div[1]/div/div[2]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
