<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>label_Reset_Password_Link_Sent_Succesfully</description>
   <name>label_Reset_Password_Link_Sent_Succesfully</name>
   <tag></tag>
   <elementGuidId>101894bc-429d-4397-90ab-224fe5981aab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;app&quot;]/div[1]/div[1]/div/h6</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
