<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>label_Forgot_Password</description>
   <name>label_Forgot_Password</name>
   <tag></tag>
   <elementGuidId>ca56f69e-4dd9-4239-9063-3fe12b1f41c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;app&quot;]/div[1]/div[1]/div/form/h6</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
