<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>label_Required_Username_Reset_Password</description>
   <name>label_Required_Username_Reset_Password</name>
   <tag></tag>
   <elementGuidId>b5ddbd6b-00af-4cec-8464-94ade54a2da2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;app&quot;]/div[1]/div[1]/div/form/div[1]/div/span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
