<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>label_Invalid_Credentials</description>
   <name>label_Invalid_Credentials</name>
   <tag></tag>
   <elementGuidId>aed1ea4d-7949-47c3-b2a4-d9c3ac54c307</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;app&quot;]/div[1]/div/div[1]/div/div[2]/div[2]/div/div[1]/div[1]/p</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
