<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>link_Forgot_Password</description>
   <name>link_Forgot_Password</name>
   <tag></tag>
   <elementGuidId>cc370a7c-91e8-4b6e-a3b7-fab76634486f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;app&quot;]/div[1]/div/div[1]/div/div[2]/div[2]/form/div[4]/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
