<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>text_box_Password</description>
   <name>text_box_Password</name>
   <tag></tag>
   <elementGuidId>31ab62e4-2c8c-427a-a8cd-8e02ec73ddd8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;app&quot;]/div[1]/div/div[1]/div/div[2]/div[2]/form/div[2]/div/div[2]/input</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
