<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>text_box_Username</description>
   <name>text_box_Username</name>
   <tag></tag>
   <elementGuidId>9ab46594-3f8a-42e2-850c-aca8b05ff0b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;app&quot;]/div[1]/div/div[1]/div/div[2]/div[2]/form/div[1]/div/div[2]/input</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
