<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>input_Visit_Date</description>
   <name>input_Visit_Date</name>
   <tag></tag>
   <elementGuidId>6e7a8bd6-12d4-4335-8d08-1f27a2573372</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;txt_visit_date&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
