<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>label_Appoinment_Confirmation</description>
   <name>label_Appoinment_Confirmation</name>
   <tag></tag>
   <elementGuidId>5bc8e155-9be4-421f-9c68-6320fe46f1ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;summary&quot;]/div/div/div[1]/h2</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
